import Link from "next/link";
import { Brand } from "@/components/brand";
import { getStaffLearningEditorData } from "@/lib/staff-learning";
import { createLesson, createQuestion, deleteQuestion, updateQuestion } from "./actions";

export const dynamic = "force-dynamic";

const input = "mt-2 h-12 w-full rounded-xl border border-[var(--border-soft)] bg-white px-4";
const textarea = "mt-2 min-h-28 w-full rounded-xl border border-[var(--border-soft)] bg-white p-4";
const label = "block text-sm font-bold";

export default async function StaffLearningPage({ searchParams }: { searchParams: Promise<{ status?: string; error?: string }> }) {
  const [data, params] = await Promise.all([getStaffLearningEditorData(), searchParams]);
  const topicMap = new Map(data.topics.map((topic) => [topic.id, topic.title]));
  return <main className="min-h-screen px-6 py-10"><div className="mx-auto max-w-6xl">
    <header className="flex flex-wrap items-center justify-between gap-4"><Brand /><nav className="flex gap-4 text-sm font-bold"><Link href={data.identity.roles.includes("teacher") ? "/teacher" : "/curator"}>В кабинет</Link><Link href="/">На сайт</Link></nav></header>
    <div className="mt-12"><p className="student-eyebrow">Учебное ядро</p><h1 className="mt-3 text-4xl font-extrabold tracking-[-.04em]">Уроки, ДЗ и банк заданий</h1><p className="mt-3 max-w-3xl text-[var(--text-muted)]">Редактор показывает только назначенные группы и предметы. Опубликованные данные сразу появляются у учеников с активной подпиской.</p></div>
    {params.status && <p role="status" className="mt-6 rounded-xl bg-[var(--brand-soft)] p-4 text-[var(--brand-burgundy)]">{params.status}</p>}
    {params.error && <p role="alert" className="mt-6 rounded-xl bg-[var(--surface-rose)] p-4 text-[var(--brand-primary)]">{params.error}</p>}

    <div className="mt-10 grid gap-8 lg:grid-cols-[1.15fr_.85fr]">
      <form action={createLesson} className="card space-y-5 p-6"><div><small className="font-bold uppercase tracking-wider text-[var(--brand-primary)]">Новый урок</small><h2 className="mt-2 text-2xl font-extrabold">Опубликовать занятие</h2></div>
        <div className="grid gap-4 sm:grid-cols-2"><label className={label}>Группа<select className={input} name="groupId" required><option value="">Выберите</option>{data.groups.map((group) => <option value={group.id} key={group.id}>{group.name} · {group.subjectName}</option>)}</select></label><label className={label}>Преподаватель<select className={input} name="teacherId"><option value="">Для преподавателя — текущий аккаунт</option>{data.groups.flatMap((group) => group.teachers).filter((teacher, index, all) => all.findIndex((item) => item.id === teacher.id) === index).map((teacher) => <option value={teacher.id} key={teacher.id}>{teacher.name}</option>)}</select></label></div>
        <label className={label}>Тема программы <span className="form-optional">необязательно</span><select className={input} name="topicId"><option value="">Без темы</option>{data.topics.map((topic) => <option value={topic.id} key={topic.id}>{topic.title}</option>)}</select></label>
        <label className={label}>Название<input className={input} name="title" minLength={3} maxLength={180} required /></label>
        <label className={label}>Описание<textarea className={textarea} name="description" maxLength={2000} /></label>
        <label className={label}>Цели урока <span className="form-optional">по одной на строку</span><textarea className={textarea} name="objectives" maxLength={1600} /></label>
        <div className="grid gap-4 sm:grid-cols-2"><label className={label}>Начало<input className={input} name="startsAt" type="datetime-local" required /></label><label className={label}>Длительность, мин<input className={input} name="durationMinutes" type="number" min={20} max={300} defaultValue={90} required /></label></div>
        <fieldset className="rounded-2xl border border-[var(--border-soft)] p-4"><legend className="px-2 font-extrabold">Материал по ссылке</legend><div className="grid gap-4 sm:grid-cols-2"><label className={label}>Название<input className={input} name="materialTitle" maxLength={180} /></label><label className={label}>HTTPS-ссылка<input className={input} name="materialUrl" type="url" maxLength={2000} /></label></div></fieldset>
        <fieldset className="rounded-2xl border border-[var(--border-soft)] p-4"><legend className="px-2 font-extrabold">Домашнее задание</legend><div className="space-y-4"><label className={label}>Название<input className={input} name="assignmentTitle" maxLength={180} /></label><label className={label}>Инструкция<textarea className={textarea} name="assignmentDescription" maxLength={3000} /></label><div className="grid gap-4 sm:grid-cols-2"><label className={label}>Дедлайн<input className={input} name="dueAt" type="datetime-local" /></label><label className={label}>Максимальный балл<input className={input} name="maxScore" type="number" min={1} max={1000} defaultValue={10} /></label></div>{data.questions.length > 0 && <div><b className="text-sm">Задания из банка</b><div className="mt-3 max-h-56 space-y-2 overflow-auto">{data.questions.filter((question) => question.status === "published").map((question) => <label className="flex gap-3 rounded-xl bg-black/5 p-3 text-sm" key={question.id}><input name="questionIds" type="checkbox" value={question.id} /><span>{question.prompt}</span></label>)}</div></div>}</div></fieldset>
        <button className="button button-primary button-large w-full">Создать урок</button>
      </form>

      <div className="space-y-8"><form action={createQuestion} className="card space-y-4 p-6"><div><small className="font-bold uppercase tracking-wider text-[var(--brand-primary)]">Банк заданий</small><h2 className="mt-2 text-2xl font-extrabold">Новое задание</h2></div><label className={label}>Предмет<select className={input} name="subjectId" required><option value="">Выберите</option>{data.subjects.map((subject) => <option value={subject.id} key={subject.id}>{subject.name}</option>)}</select></label><label className={label}>Тема<select className={input} name="topicId"><option value="">Без темы</option>{data.topics.map((topic) => <option value={topic.id} key={topic.id}>{topic.title}</option>)}</select></label><label className={label}>Условие<textarea className={textarea} name="prompt" required maxLength={4000} /></label><label className={label}>Ответ<textarea className={textarea} name="answer" required maxLength={4000} /></label><div className="grid gap-4 sm:grid-cols-2"><label className={label}>Сложность<select className={input} name="difficulty" defaultValue="2"><option value="1">Базовая</option><option value="2">Средняя</option><option value="3">Высокая</option></select></label><label className={label}>Статус<select className={input} name="status" defaultValue="published"><option value="published">Опубликовано</option><option value="draft">Черновик</option></select></label></div><button className="button button-primary w-full">Добавить в банк</button></form>
        <section className="card p-6"><h2 className="text-xl font-extrabold">Последние уроки</h2><div className="mt-4 divide-y divide-[var(--border-soft)]">{data.lessons.length ? data.lessons.map((lesson) => <div className="py-4" key={lesson.id}><b>{lesson.title}</b><p className="mt-1 text-sm text-[var(--text-muted)]">{lesson.groupName} · {lesson.subjectName} · {lesson.status}</p></div>) : <p className="py-4 text-[var(--text-muted)]">Уроков пока нет.</p>}</div></section>
      </div>
    </div>

    <section className="mt-8"><h2 className="text-2xl font-extrabold">Редактирование банка</h2><div className="mt-5 grid gap-5 md:grid-cols-2">{data.questions.map((question) => <form action={updateQuestion} className="card space-y-4 p-5" key={question.id}><input type="hidden" name="questionId" value={question.id} /><label className={label}>Предмет<select className={input} name="subjectId" defaultValue={question.subject_id}>{data.subjects.map((subject) => <option value={subject.id} key={subject.id}>{subject.name}</option>)}</select></label><label className={label}>Тема<select className={input} name="topicId" defaultValue={question.topic_id ?? ""}><option value="">Без темы</option>{data.topics.map((topic) => <option value={topic.id} key={topic.id}>{topic.title}</option>)}</select></label><label className={label}>Условие<textarea className={textarea} name="prompt" defaultValue={question.prompt} required /></label><label className={label}>Ответ<textarea className={textarea} name="answer" defaultValue={question.answer} required /></label><div className="grid grid-cols-2 gap-3"><select className={input} name="difficulty" defaultValue={question.difficulty}><option value="1">Базовая</option><option value="2">Средняя</option><option value="3">Высокая</option></select><select className={input} name="status" defaultValue={question.status}><option value="published">Опубликовано</option><option value="draft">Черновик</option></select></div><p className="text-xs text-[var(--text-muted)]">{question.topic_id ? topicMap.get(question.topic_id) : "Без темы"}</p><div className="flex gap-3"><button className="button button-primary flex-1">Сохранить</button><button formAction={deleteQuestion} className="button flex-1" name="questionId" value={question.id}>Удалить</button></div></form>)}</div></section>
  </div></main>;
}
